### ISSUE TITLE
About Bounding Box

### ISSUE THREAD

**Issue by tianjiu233** [chrisckri/InstanceSegmentation_Sentinel2#1]
Hi Chrieke,
I have read your thesis and want to reimplement it with mask-rcnn.
And I have one question it.
When doing instance segmentation, the bounding box is required.

In your paper, it does describe how to generate the bounding box from the segmentation label or vector label. I am really crious about that.
Would you mind telling me?
Thx

**Comment by chrieke** [comment]
Hi, finally uploaded a first few scripts of the code. Getting the bounding box from a shapely Polygon is as easy as poly.bounds. However, the COCO format required for FCIS and probably also Mask-RCNN requires the cocojson format, which uses a different string encoding of the Polygon and bounding box, see [here](https://github.com/chrieke/InstanceSegmentation_Sentinel2/blob/master/preprocessing/preprocessing_chips_coco.py#L195).

**Comment by tianjiu233** [comment]
thx for your help!
