### ISSUE TITLE
which version of Deep Learning AMI is used?

### ISSUE THREAD

**Issue by CarlosAndres12** [chrisckri/InstanceSegmentation_Sentinel2#10]
![image](https://user-images.githubusercontent.com/8310276/71739549-c57b0f00-2e27-11ea-9e54-b403ccc3a0fa.png)

i am not sure which to select.

**Comment by chrieke** [comment]
@CarlosAndres12 Hi, at the time the Ubuntu 14.04 AMI was used, but try with 16.04. Also have a look at this suggestion of Facebook's Detectron library, which contain much more modern model implementations https://github.com/chrieke/InstanceSegmentation_Sentinel2/issues/8#issuecomment-565844437
