### ISSUE TITLE
How to get coordinates of predicted boundaries?

### ISSUE THREAD

**Issue by bkavlak** [chrisckri/InstanceSegmentation_Sentinel2#11]
Hi,

As you suggested, I applied detectron2 architecture to your process flow and it seems promising. I have a problem at the last stage when we need the boundaries as coordinates. I'd happy to share my work and discuss on it if we may contact.

My problem is basically that an outcome from the detectron2 model is a predicted binary masks [a single polygon] as [128x128]. I guess we need to assign coordinates to values with 1 and convert it to a polygon. How should we determine the coordinates in a flow of images?

If you've already done such a process and may give hints about your method, it'd help anyone trying to get field boundaries with deep learning architectures since they tend to be designed for digital images rather than satellite images.

Thanks!

**Comment by thipokKub** [comment]
Hello, I'm am not sure that this will help or not but here it is
I tested with TFRecord (from Google Earth Engine), and this is my method

In case for TFRecord, there exists an additional file with useful information called `mixer` file. It is automatically exported along with TFRecord files. I first read TFRecord as numpy array. Then perform model inference and get some output back. At this point the output is usually a tensor with no geo-spatial information, this where you plug-in the original (from `mixer` file)  CRS and affine transforms back. For simple code

```python
import json
import rasterio
from rasterio import Affine as A

mixer = json.loads("<MIXER HERE".json")
crs = {'init': mixer['projection']['crs']}
transform = A(*mixer["projection"]["affine"]["doubleMatrix"])

#...DO OPERATIONS...
#...DO PREDICTIONS -> Do save output as a numpy array at `out` variable
new_dataset = rasterio.open(
    'new.tif',
    'w',
    driver='GTiff',
    height=out.shape[0],
    width=out.shape[1],
    count=1,
    dtype=out.dtype,
    crs='+proj=latlong',
    transform=transform,
    compress="LZMA"
)
new_dataset.write(out, 1)
new_dataset.close()
```

With a little bit of research, I believe from the original GeoTIFF image, you can extract both CRS and affine transforms tensor and apply the same code. I think it somewhere along the line of

```python
dataset = rasterio.open('example.tif')
crs = dataset.crs
transforms = dataset.transform
# ...DO STUFF
```
Ref: [https://rasterio.readthedocs.io/en/latest/quickstart.html](https://rasterio.readthedocs.io/en/latest/quickstart.html)

I am not sure on how to apply transforms on Polygon though, you might have to do a little bit more research. Hope this help!

**Comment by bkavlak** [comment]
Thank you @thipokKub ! I used detectron2, which uses PyTorch actually, but I will try a sth with TF, as well.

I gave a break to develop instance segmentation model. My final thoughts were keeping the extends of the image chips and then assigning them to the mask arrays.
