### ISSUE TITLE
2016 LPIS dataset ("Marker_2016_CVR.zip")

### ISSUE THREAD

**Issue by CarlosAndres12** [chrisckri/InstanceSegmentation_Sentinel2#12]
I am looking for the 2016 LPIS dataset ("Marker_2016_CVR.zip") but download page(https://kortdata.fvm.dk/download/Markblokke_Marker?page=MarkerHistoriske) seems to be down, is there another way to access  the data?

Thanks.

**Comment by chrieke** [comment]
Yeah it seems the dataset is not publicly available anymore, searched for it extensively but could not find it. Hope they put the collections back up, ~~in the meantime here is the 2016 Marker dataset.~~
Please access the Denmark and other LPIS datasets via the [Eurocrops project](https://github.com/maja601/EuroCrops).
