### ISSUE TITLE
Segmentation id is not unique in preprocesseing pipeline

### ISSUE THREAD

**Issue by thipokKub** [chrisckri/InstanceSegmentation_Sentinel2#3]
The preprocessing code cannot be used directly with standard COCO dataset because segmentation id is not unique

Code suggestion is to fix `coco.py` in function `format_coco` from
```
key_annotation = {"id": key_idx, ...
```
to
```
id_counter = 20000000
for key_idx, key in enumerate(chip_dfs.keys()):
    ...
    key_annotation = {"id": id_counter, ...
    id_counter += 1
```

**Comment by chrieke** [comment]
Thank you for catching this! Fixed and also added some additional instructions and tips regarding the coco structure for future users.
Is similar in my original code for the thesis&results, but when improving it for publishing this must have slipped, should have compared the datasets more thoroughly.
