### ISSUE TITLE
Preprocessing notebook throwing CRSError

### ISSUE THREAD

**Issue by jman278** [chrisckri/InstanceSegmentation_Sentinel2#4]
CRSError: CRS appears to be JSON but is not valid

**Comment by chrieke** [comment]
@jman278 Hi, thanks for the error message. Still works for me, could you post the error trace (more lines of the error message so that I can see where and what is causing the problem).

**Comment by jman278** [comment]
Hi chrieke,

I got it to work after updating the function as:

def prepare_vector(fp, out_crs, clipping_bounds): 
    df = (gpd.read_file(str(fp), encoding='cp865')  # danish encoding 
             .to_crs(epsg=32632) 
             .rename(columns={'Afgroede': 'lc_name', 'AfgKode': 'lc_id', 'JOURNALNUM': 'journalnr'}) 
             .drop(['GB', 'GEOMETRISK', 'MARKNUMMER'], axis=1) 
             .pipe(utils.geo.explode_mp) 
             .pipe(utils.geo.buffer_zero) 
             .pipe(utils.geo.close_holes) 
             .pipe(utils.geo.set_crs, 3044) 
             .pipe(utils.geo.clip, clip_poly=shapely.geometry.box(*clipping_bounds), explode_mp_=True) 
             .pipe(utils.geo.reclassify_col, rcl_scheme=utils.geo.reclass_legend,  
                   col_classlabels='lc_name', col_classids='lc_id', drop_other_classes=True) 
             .assign(geometry=lambda _df: _df.geometry.simplify(5, preserve_topology=True)) 
             .pipe(utils.geo.buffer_zero) 
             .assign(area_sqm=lambda _df: _df.geometry.area) 
             .pipe(utils.geo.reduce_precision, precision=4) 
             .reset_index(drop=True) 
             .assign(fid=lambda _df: range(0, len(_df.index))) 
             .filter(['journalnr', 'lc_id', 'lc_name', 'r_lc_id', 'r_lc_name', 'area_sqm', 'fid', 'geometry']))
    return df 


Thanks!
