### ISSUE TITLE
Steps to run your pretrained model on a tif file

### ISSUE THREAD

**Issue by jman278** [chrisckri/InstanceSegmentation_Sentinel2#5]
Hi @chrieke ,

Can you please tell the steps to do run your pretrained model on one of my .tif files?
Is it necessary to have a .shp file for testing on the .tif?

Also, is there a way to visualize the instance segmentation proposals using the detections_val2016_results.json file?

**Comment by MichaelAshton** [comment]
Hi @jman278,

Were you able to run the pretrained model on a tif file and/or visualize the proposals? i'm trying to figure it out.

**Comment by jman278** [comment]
> Hi @jman278,
> 
> Were you able to run the pretrained model on a tif file and/or visualize the proposals? i'm trying to figure it out.

@MichaelAshton 

You can edit and run fcis/demo.py using your trained model on your images.
