### ISSUE TITLE
YAML typo & instance_vals2016

### ISSUE THREAD

**Issue by bkavlak** [chrisckri/InstanceSegmentation_Sentinel2#7]
Hi,

There are some changes needed in the YAML file:

Line 57: train2014 ---> train2016
Line 59: vals2014 ---> vals2016
Line 142: TEST:s ---> TEST:

Also in Annotations:

vals2016 -> instance_vals2016
train2016 -> instance_train2016

I guess the script expects these values.

**Comment by chrieke** [comment]
Thanks, fixed. The config file allows you to set your own naming conventions.
